### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by GMartigny**
Update all outdated dependencies (especially jsdom).
Remove all node security warning.
Update tests.

### CODE REVIEW

**Comment by lukechilds** [comment]
@GMartigny Thankyou so much! ✨

**Comment by lukechilds** [comment]
@GMartigny Just published `window@4.2.6`

**Comment by GMartigny** [comment]
No problem.

You might want to update [browser-env](https://github.com/lukechilds/browser-env) as well. Should I do a PR ?

**Comment by lukechilds** [comment]
If you could that would be great 👌

**Pull request merged**
